// https://github.com/Justineo/vue-awesome
// overview of icons: https://fontawesome.com/v4.7.0/icon

import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon'

Vue.component('el-icon', Icon)

import 'vue-awesome/icons/rss'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/home'
import 'vue-awesome/icons/user'
import 'vue-awesome/icons/plus'
import 'vue-awesome/icons/users'
import 'vue-awesome/icons/times'
import 'vue-awesome/icons/spinner'
import 'vue-awesome/icons/user-plus'
import 'vue-awesome/icons/tachometer-alt'
import 'vue-awesome/icons/regular/copy'
import 'vue-awesome/icons/regular/envelope'
import 'vue-awesome/icons/arrow-left'
import 'vue-awesome/icons/arrow-right'
import 'vue-awesome/icons/sign-in-alt'
import 'vue-awesome/icons/sign-out-alt'
import 'vue-awesome/icons/bell'
import 'vue-awesome/icons/bell-slash'
import 'vue-awesome/icons/caret-up'
import 'vue-awesome/icons/caret-down'
import 'vue-awesome/icons/user-secret'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/lock'
import 'vue-awesome/icons/chevron-right'
import 'vue-awesome/icons/chevron-left'
import 'vue-awesome/icons/cog'
import 'vue-awesome/icons/chart-bar'
import 'vue-awesome/icons/expand-arrows-alt'
import 'vue-awesome/icons/download'
import 'vue-awesome/icons/filter'
import 'vue-awesome/icons/calendar'
import 'vue-awesome/icons/copy'
import 'vue-awesome/icons/columns'
import 'vue-awesome/icons/address-book'
import 'vue-awesome/icons/broadcast-tower'
import 'vue-awesome/icons/thumbtack'
import 'vue-awesome/icons/trash'
import 'vue-awesome/icons/upload'
import 'vue-awesome/icons/edit'
import 'vue-awesome/icons/circle'
import 'vue-awesome/icons/question-circle'
import 'vue-awesome/icons/music'
import 'vue-awesome/icons/cloud'
import 'vue-awesome/icons/file'
import 'vue-awesome/icons/clipboard-list'
import 'vue-awesome/icons/sync'
import 'vue-awesome/icons/link'
import 'vue-awesome/icons/cloud-download-alt'
import 'vue-awesome/icons/list-ul'
import 'vue-awesome/icons/globe'
import 'vue-awesome/icons/male'
import 'vue-awesome/icons/external-link-alt'
import 'vue-awesome/icons/unlink'
